# Generated by Django 3.1.3 on 2020-12-07 03:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('itemsearchapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'itemsearchapp_item',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='item',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
