# Generated by Django 3.1.3 on 2020-12-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsearchapp', '0002_auto_20201206_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
    ]
