# Generated by Django 3.1.3 on 2020-12-09 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsearchapp', '0003_auto_20201208_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
