# Generated by Django 3.1.3 on 2020-12-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemsearchapp', '0004_auto_20201208_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
